version: "3.8"
services:
  db:
    image: mysql:8.0
    volumes:
      - ./.mysql:/var/lib/mysql:rw
      - ./mysql-dev-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    networks:
      - default

networks:
  default:
    driver: bridge
